server:
  port: 8090
spring:
  profiles:
    active: dev
  cache:
   type: redis
  redis:
   host: 127.0.0.1
   port: 6379
   timeout: 5000
   database: 0
   jedis:
     pool:
       max-active: 100
       max-wait: -1ms
       max-idle: 8
       min-idle: 0